locale: 'fr'

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true

publish_mode: editorial_workflow

media_library:
  name: uploadcare
  config:
    publicKey: "52902d5ce7ef26c71044"
  settings:
    autoFilename: false

collections:
  - label: "Pages"
    name: pages
    files:
      - label: "Page d'accueil"
        name: home
        file: src/assets/data/home.json
        fields:
          - label: "Citation"
            name: sentence
            widget: string
          - label: "Auteur"
            name: author
            widget: string
          - label: "Prestations"
            name: prestations
            widget: list
            allow_add: false
            fields:
              - { label: "Titre", name: title, widget: text }
              - { label: "Description", name: description, widget: text }
              - { label: "Arrière-plan", name: backgroundImage, widget: image }
              - label: "Dégradé"
                name: "overlay"
                widget: "select"
                options: [ "left", "foo" ]
              - label: "Position de l'arrière-plan"
                name: backgroundPosition
                widget: string
                required: false
  - label: "Prestations"
    name: prestations
    folder: src/assets/data/prestations
    create: true
    fields:
      - label: "Contenu"
        name: content
        widget: markdown
      - label: "Galerie"
        name: gallery
        widget: list
        summary: '{{fields.image}}'
        fields:
          - label: "Image"
            name: image
            widget: image